name: checkoutin
description: Aplikasi Thrifting terbaik
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  circle_nav_bar: ^2.0.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - lib/images/
